defaults: &defaults
  instagram_root_url: 'https://www.instagram.com'
  instagram_login_url: 'https://www.instagram.com/accounts/login'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
